#ifndef __ascii_keycode_table_h__
#define __ascii_keycode_table_h__

#include "usage_page.h"

// Lookup table to convert ascii characters in to keyboard scan codes
// Format: most signifficant bit indicates if scan code should be sent with shift modifier
// remaining 7 bits are to be used as scan code number.

#define SHIFT(keycode) (keycode | 0x80)

const unsigned char ascii_to_keycode[] PROGMEM = {
  /* ASCII   0: NUL   */ NULL,
  /* ASCII   1: SOH   */ NULL,
  /* ASCII   2: STX   */ NULL,
  /* ASCII   3: ETX   */ NULL,
  /* ASCII   4: EOT   */ NULL,
  /* ASCII   5: ENQ   */ NULL,
  /* ASCII   6: ACK   */ NULL,
  /* ASCII   7: BEL   */ NULL,
  /* ASCII   8: BS    */ Keycodes::Keyboard_Backspace,
  /* ASCII   9: TAB   */ Keycodes::Keyboard_Tab,
  /* ASCII  10: LF    */ Keycodes::Keyboard_Return,
  /* ASCII  11: VT    */ NULL,
  /* ASCII  12: FF    */ NULL,
  /* ASCII  13: CR    */ NULL,
  /* ASCII  14: SO    */ NULL,
  /* ASCII  15: SI    */ NULL,
  /* ASCII  16: DLE   */ NULL,
  /* ASCII  17: DC1   */ NULL,
  /* ASCII  18: DC2   */ NULL,
  /* ASCII  19: DC3   */ NULL,
  /* ASCII  20: DC4   */ NULL,
  /* ASCII  21: NAK   */ NULL,
  /* ASCII  22: SYN   */ NULL,
  /* ASCII  23: ETB   */ NULL,
  /* ASCII  24: CAN   */ NULL,
  /* ASCII  25: EM    */ NULL,
  /* ASCII  26: SUB   */ NULL,
  /* ASCII  27: ESC   */ Keycodes::Keyboard_Escape,
  /* ASCII  28: FS    */ NULL,
  /* ASCII  29: GS    */ NULL,
  /* ASCII  30: RS    */ NULL,
  /* ASCII  31: US    */ NULL,
  /* ASCII  32: Space */ Keycodes::Keyboard_Spacebar,
  /* ASCII  33: !     */ SHIFT(Keycodes::Keyboard_1),
  /* ASCII  34: "     */ SHIFT(Keycodes::Keyboard_Quote),
  /* ASCII  35: #     */ SHIFT(Keycodes::Keyboard_3),
  /* ASCII  36: $     */ SHIFT(Keycodes::Keyboard_4),
  /* ASCII  37: %     */ SHIFT(Keycodes::Keyboard_5),
  /* ASCII  38: &     */ SHIFT(Keycodes::Keyboard_7),
  /* ASCII  39: '     */ Keycodes::Keyboard_Quote,
  /* ASCII  40: (     */ SHIFT(Keycodes::Keyboard_9),
  /* ASCII  41: )     */ SHIFT(Keycodes::Keyboard_0),
  /* ASCII  42: *     */ SHIFT(Keycodes::Keyboard_8),
  /* ASCII  43: +     */ SHIFT(Keycodes::Keyboard_Equals),
  /* ASCII  44: ,     */ Keycodes::Keyboard_Comma,
  /* ASCII  45: -     */ Keycodes::Keyboard_Hyphen,
  /* ASCII  46: .     */ Keycodes::Keyboard_Period,
  /* ASCII  47: /     */ Keycodes::Keyboard_Slash,
  /* ASCII  48: 0     */ Keycodes::Keyboard_0,
  /* ASCII  49: 1     */ Keycodes::Keyboard_1,
  /* ASCII  50: 2     */ Keycodes::Keyboard_2,
  /* ASCII  51: 3     */ Keycodes::Keyboard_3,
  /* ASCII  52: 4     */ Keycodes::Keyboard_4,
  /* ASCII  53: 5     */ Keycodes::Keyboard_5,
  /* ASCII  54: 6     */ Keycodes::Keyboard_6,
  /* ASCII  55: 7     */ Keycodes::Keyboard_7,
  /* ASCII  56: 8     */ Keycodes::Keyboard_8,
  /* ASCII  57: 9     */ Keycodes::Keyboard_9,
  /* ASCII  58: :     */ SHIFT(Keycodes::Keyboard_Semicolon),
  /* ASCII  59: ;     */ Keycodes::Keyboard_Semicolon,
  /* ASCII  60: <     */ SHIFT(Keycodes::Keyboard_Comma),
  /* ASCII  61: =     */ Keycodes::Keyboard_Equals,
  /* ASCII  62: >     */ SHIFT(Keycodes::Keyboard_Period),
  /* ASCII  63: ?     */ SHIFT(Keycodes::Keyboard_Slash),
  /* ASCII  64: @     */ SHIFT(Keycodes::Keyboard_2),
  /* ASCII  65: A     */ SHIFT(Keycodes::Keyboard_A),
  /* ASCII  66: B     */ SHIFT(Keycodes::Keyboard_B),
  /* ASCII  67: C     */ SHIFT(Keycodes::Keyboard_C),
  /* ASCII  68: D     */ SHIFT(Keycodes::Keyboard_D),
  /* ASCII  69: E     */ SHIFT(Keycodes::Keyboard_E),
  /* ASCII  70: F     */ SHIFT(Keycodes::Keyboard_F),
  /* ASCII  71: G     */ SHIFT(Keycodes::Keyboard_G),
  /* ASCII  72: H     */ SHIFT(Keycodes::Keyboard_H),
  /* ASCII  73: I     */ SHIFT(Keycodes::Keyboard_I),
  /* ASCII  74: J     */ SHIFT(Keycodes::Keyboard_J),
  /* ASCII  75: K     */ SHIFT(Keycodes::Keyboard_K),
  /* ASCII  76: L     */ SHIFT(Keycodes::Keyboard_L),
  /* ASCII  77: M     */ SHIFT(Keycodes::Keyboard_M),
  /* ASCII  78: N     */ SHIFT(Keycodes::Keyboard_N),
  /* ASCII  79: O     */ SHIFT(Keycodes::Keyboard_O),
  /* ASCII  80: P     */ SHIFT(Keycodes::Keyboard_P),
  /* ASCII  81: Q     */ SHIFT(Keycodes::Keyboard_Q),
  /* ASCII  82: R     */ SHIFT(Keycodes::Keyboard_R),
  /* ASCII  83: S     */ SHIFT(Keycodes::Keyboard_S),
  /* ASCII  84: T     */ SHIFT(Keycodes::Keyboard_T),
  /* ASCII  85: U     */ SHIFT(Keycodes::Keyboard_U),
  /* ASCII  86: V     */ SHIFT(Keycodes::Keyboard_V),
  /* ASCII  87: W     */ SHIFT(Keycodes::Keyboard_W),
  /* ASCII  88: X     */ SHIFT(Keycodes::Keyboard_X),
  /* ASCII  89: Y     */ SHIFT(Keycodes::Keyboard_Y),
  /* ASCII  90: Z     */ SHIFT(Keycodes::Keyboard_Z),
  /* ASCII  91: [     */ Keycodes::Keyboard_OpenBracket,
  /* ASCII  92: \     */ Keycodes::Keyboard_Backslash,
  /* ASCII  93: ]     */ Keycodes::Keyboard_CloseBracket,
  /* ASCII  94: ^     */ SHIFT(Keycodes::Keyboard_6),
  /* ASCII  95: _     */ SHIFT(Keycodes::Keyboard_Hyphen),
  /* ASCII  96: `     */ Keycodes::Keyboard_GraveAccent,
  /* ASCII  97: a     */ Keycodes::Keyboard_A,
  /* ASCII  98: b     */ Keycodes::Keyboard_B,
  /* ASCII  99: c     */ Keycodes::Keyboard_C,
  /* ASCII 100: d     */ Keycodes::Keyboard_D,
  /* ASCII 101: e     */ Keycodes::Keyboard_E,
  /* ASCII 102: f     */ Keycodes::Keyboard_F,
  /* ASCII 103: g     */ Keycodes::Keyboard_G,
  /* ASCII 104: h     */ Keycodes::Keyboard_H,
  /* ASCII 105: i     */ Keycodes::Keyboard_I,
  /* ASCII 106: j     */ Keycodes::Keyboard_J,
  /* ASCII 107: k     */ Keycodes::Keyboard_K,
  /* ASCII 108: l     */ Keycodes::Keyboard_L,
  /* ASCII 109: m     */ Keycodes::Keyboard_M,
  /* ASCII 110: n     */ Keycodes::Keyboard_N,
  /* ASCII 111: o     */ Keycodes::Keyboard_O,
  /* ASCII 112: p     */ Keycodes::Keyboard_P,
  /* ASCII 113: q     */ Keycodes::Keyboard_Q,
  /* ASCII 114: r     */ Keycodes::Keyboard_R,
  /* ASCII 115: s     */ Keycodes::Keyboard_S,
  /* ASCII 116: t     */ Keycodes::Keyboard_T,
  /* ASCII 117: u     */ Keycodes::Keyboard_U,
  /* ASCII 118: v     */ Keycodes::Keyboard_V,
  /* ASCII 119: w     */ Keycodes::Keyboard_W,
  /* ASCII 120: x     */ Keycodes::Keyboard_X,
  /* ASCII 121: y     */ Keycodes::Keyboard_Y,
  /* ASCII 122: z     */ Keycodes::Keyboard_Z,
  /* ASCII 123: {     */ SHIFT(Keycodes::Keyboard_OpenBracket),
  /* ASCII 124: |     */ SHIFT(Keycodes::Keyboard_Backslash),
  /* ASCII 125: }     */ SHIFT(Keycodes::Keyboard_CloseBracket),
  /* ASCII 126: ~     */ SHIFT(Keycodes::Keyboard_GraveAccent),
  /* ASCII 127: DEL   */ Keycodes::Keyboard_Delete
};

#endif